controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    summit_velocity_controller:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["summit_front_left_wheel_joint", "summit_back_left_wheel_joint"]
      right_wheel_names: ["summit_front_right_wheel_joint", "summit_back_right_wheel_joint"]
      wheel_separation: 0.4  # Distance entre les roues gauche et droite
      wheel_radius: 0.1      # Rayon des roues